"""empty message

Revision ID: 03142bd1cf21
Revises: f7ac1da342a1
Create Date: 2020-09-02 22:55:53.642255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03142bd1cf21'
down_revision = 'f7ac1da342a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
