"""empty message

Revision ID: 27b0d776d24b
Revises: 53aec3ce65fa
Create Date: 2020-09-02 19:07:50.011045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b0d776d24b'
down_revision = '53aec3ce65fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
