"""empty message

Revision ID: 337a1ee6167f
Revises: 39c639763aa8
Create Date: 2020-09-02 18:28:10.604839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337a1ee6167f'
down_revision = '39c639763aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
