"""empty message

Revision ID: 53aec3ce65fa
Revises: 337a1ee6167f
Create Date: 2020-09-02 18:28:41.641256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53aec3ce65fa'
down_revision = '337a1ee6167f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
