"""empty message

Revision ID: 80c63f706d1b
Revises: 8fce9e034825
Create Date: 2020-09-02 01:30:08.042926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c63f706d1b'
down_revision = '8fce9e034825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_replay_association',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('replay_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['replay_id'], ['replays.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'replay_id')
    )
    op.drop_constraint('replays_player_2_id_fkey', 'replays', type_='foreignkey')
    op.drop_constraint('replays_player_1_id_fkey', 'replays', type_='foreignkey')
    op.drop_column('replays', 'player_2_id')
    op.drop_column('replays', 'player_1_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replays', sa.Column('player_1_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('replays', sa.Column('player_2_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('replays_player_1_id_fkey', 'replays', 'players', ['player_1_id'], ['id'])
    op.create_foreign_key('replays_player_2_id_fkey', 'replays', 'players', ['player_2_id'], ['id'])
    op.drop_table('player_replay_association')
    # ### end Alembic commands ###
