"""empty message

Revision ID: 8fce9e034825
Revises: 
Create Date: 2020-09-02 00:05:27.797412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fce9e034825'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_hash', postgresql.BYTEA(length=32), nullable=False),
    sa.Column('map_name', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('tile_set', sa.String(), nullable=False),
    sa.Column('camera_top', sa.Integer(), nullable=False),
    sa.Column('camera_left', sa.Integer(), nullable=False),
    sa.Column('camera_bottom', sa.Integer(), nullable=False),
    sa.Column('camera_right', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maps_file_hash'), 'maps', ['file_hash'], unique=True)
    op.create_table('replay_data_path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('replay_data_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clan_name', sa.String(), nullable=False),
    sa.Column('clan_tag', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_clan_tag'), 'teams', ['clan_tag'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pro_name', sa.String(length=12), nullable=True),
    sa.Column('nationality', sa.String(length=2), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pro_name')
    )
    op.create_table('battle_net_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.Integer(), nullable=False),
    sa.Column('realm', sa.Integer(), nullable=False),
    sa.Column('ladder_id', sa.Integer(), nullable=True),
    sa.Column('favorite_race', sa.Enum('PROTOSS', 'TERRAN', 'ZERG', name='race'), nullable=True),
    sa.Column('clan_tag', sa.String(length=6), nullable=True),
    sa.Column('clan_name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(length=12), nullable=True),
    sa.Column('mmr', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('previous_rank', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('join_timestamp', sa.DateTime(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_locator', 'battle_net_info', ['profile_id', 'region', 'realm'], unique=True)
    op.create_table('replays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_hash', postgresql.BYTEA(length=32), nullable=True),
    sa.Column('original_path', postgresql.BYTEA(), nullable=True),
    sa.Column('versions', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('real_length', sa.Interval(), nullable=False),
    sa.Column('expansion', sa.String(length=6), nullable=False),
    sa.Column('frames', sa.Integer(), nullable=False),
    sa.Column('game_fps', sa.Float(), nullable=False),
    sa.Column('real_type', sa.String(length=6), nullable=False),
    sa.Column('is_ladder', sa.Boolean(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('speed', sa.String(length=8), nullable=False),
    sa.Column('region', sa.String(length=2), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('player_1_id', sa.Integer(), nullable=True),
    sa.Column('player_2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.ForeignKeyConstraint(['player_1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_2_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replays_file_hash'), 'replays', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replays_file_hash'), table_name='replays')
    op.drop_table('replays')
    op.drop_index('idx_locator', table_name='battle_net_info')
    op.drop_table('battle_net_info')
    op.drop_table('players')
    op.drop_index(op.f('ix_teams_clan_tag'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('replay_data_path')
    op.drop_index(op.f('ix_maps_file_hash'), table_name='maps')
    op.drop_table('maps')
    # ### end Alembic commands ###
