"""empty message

Revision ID: 90fb66cae0fb
Revises: a9f6510712f0
Create Date: 2020-09-02 21:22:41.939431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fb66cae0fb'
down_revision = 'a9f6510712f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
