"""empty message

Revision ID: a9f6510712f0
Revises: 27b0d776d24b
Create Date: 2020-09-02 19:21:11.391554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f6510712f0'
down_revision = '27b0d776d24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battle_net_info_replay_association', sa.Column('battle_net_info_id', sa.Integer(), nullable=False))
    op.drop_constraint('battle_net_info_replay_association_player_id_fkey', 'battle_net_info_replay_association', type_='foreignkey')
    op.create_foreign_key(None, 'battle_net_info_replay_association', 'battle_net_info', ['battle_net_info_id'], ['id'])
    op.drop_column('battle_net_info_replay_association', 'player_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battle_net_info_replay_association', sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'battle_net_info_replay_association', type_='foreignkey')
    op.create_foreign_key('battle_net_info_replay_association_player_id_fkey', 'battle_net_info_replay_association', 'battle_net_info', ['player_id'], ['id'])
    op.drop_column('battle_net_info_replay_association', 'battle_net_info_id')
    # ### end Alembic commands ###
