"""empty message

Revision ID: c8fe0d198d4e
Revises: 90fb66cae0fb
Create Date: 2020-09-02 21:24:11.983861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8fe0d198d4e'
down_revision = '90fb66cae0fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
