"""empty message

Revision ID: f7ac1da342a1
Revises: c8fe0d198d4e
Create Date: 2020-09-02 21:33:51.567994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ac1da342a1'
down_revision = 'c8fe0d198d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
